# -name: sp
# host: localhost
# task: collection of the details
# -name: Prasanna


- name: sp
  hosts: frontend
  tasks: #collection of the details
    - name: Prasanna
      debug:
        msg: it is successful with ansible command
  